import Head from "next/head";
import { GetStaticProps } from "next";
import Link from "next/link";

export interface Props {
  userId: number;
  id: number;
  title: string;
  body: string;
}
export interface DataProps {
  data: Props[];
}
export default function Home({ data }: DataProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-8 text-5xl font-semibold text-center font-raleway underline underline-offset-4 text-slate-600">
        Blog Container
      </div>
      <main className="w-full px-5 my-5 mx-auto lg:w-8/12 grid lg:grid-cols-3 grid-cols-1 gap-12 lg:p-10 font-raleway text-lg text-slate-600">
        {data.map((el, i) => (
          <Link
            href={`/posts/${el.id}`}
            className="w-full py-6 px-4 lg:px-10 text-center border border-gray-50 hover:border-lime-200 shadow
  lg:hover:scale-110 lg:hover:bg-lime-100 transition delay-150 duration-300 ease-in-out"
            key={i}
          >
            <div className="text-4xl py-4 text-lime-600 font-bold">
              Blog {el.id}
            </div>
            <div key={i}>{el.title}</div>
          </Link>
        ))}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=10"
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
};
